<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Campo\\' => array($vendorDir . '/campo/random-user-agent/src'),
);
