<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf7dcdc0a0a43d2580eef2f3fc4591055
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Campo\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Campo\\' => 
        array (
            0 => __DIR__ . '/..' . '/campo/random-user-agent/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf7dcdc0a0a43d2580eef2f3fc4591055::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf7dcdc0a0a43d2580eef2f3fc4591055::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf7dcdc0a0a43d2580eef2f3fc4591055::$classMap;

        }, null, ClassLoader::class);
    }
}
